name: Deploy naar mijn.host

on:
  push:
    branches:
      - main
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via FTP (productie)
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/audio/**

      - name: Upload via FTP (dev)
        if: github.ref == 'refs/heads/dev'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR_DEV }}
          protocol: ftp
          exclude: |
            **/.git*
            **/.git*/**
            **/audio/**
